name: CI
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: python -m pip install -U pip && pip install -r requirements.txt ruff
    - name: Build fixture data
      run: |
        python - <<'PY'
        import pandas as pd, numpy as np, pathlib
        pathlib.Path('01_data').mkdir(exist_ok=True)
        syms=[f'T{i:04d}' for i in range(1,1001)]
        df=pd.DataFrame({'date':['2025-08-29']*len(syms),
                         'symbol':syms,
                         'AdjC':np.linspace(5,50,len(syms)),
                         'ADV21':list(range(len(syms),0,-1))})
        df.to_parquet('01_data/px.parquet', index=False)
        print('OK fixture 01_data/px.parquet')
        PY
    - name: Lint
      run: ruff check .
    - run: python 02_universe/build_universe.py
    - run: python 03_factors_raw/build_factors.py
    - run: python 14_testing_runbook/qc_all.py
